import fs from "node:fs"
import { PermissionFlagsBits } from "discord.js"

const ROLE_PERMISSIONS_SCHEMA_TEMPLATE = `# This file is automatically generated. Do not edit.
type: array
description: (Optional) A list of permissions for this role.
items:
  type: string
  description: A permission name (e.g., "SendMessages", "ManageRoles").
  enum:`

const OVERWRITES_PERMISSIONS_SCHEMA_TEMPLATE = `# This file is automatically generated. Do not edit.
type: object
properties:`

function generateRolePermissionsSchema() {
  let content = ROLE_PERMISSIONS_SCHEMA_TEMPLATE

  Object.keys(PermissionFlagsBits).forEach((key) => {
    content += `\n    - ${key}`
  })

  fs.writeFileSync("./src/schemas/role-permissions.schema.gen.yml", content)
}

function generateOverwritesPermissionsSchema() {
  let content = OVERWRITES_PERMISSIONS_SCHEMA_TEMPLATE

  Object.keys(PermissionFlagsBits).forEach((key) => {
    content += `\n  ${key}:
    type: string
    enum:
      - Allow
      - Deny
      - Default`
  })

  fs.writeFileSync("./src/schemas/overwrites-permissions.schema.gen.yml", content)
}

generateRolePermissionsSchema()
generateOverwritesPermissionsSchema()
