import fs from "node:fs"
import { PermissionFlagsBits } from "discord.js"

function writeSchema(schema: any, path: string) {
  const content = `${JSON.stringify(schema, null, 2)}`.replace(`"__comment__": true,`, "// This file is automatically generated. Do not edit.").replace("__comment__", "// This file is automatically generated. Do not edit.")
  fs.writeFileSync(path, content)
}

function generateRolePermissionsSchema() {
  const schema = {
    __comment__: true,
    id: "https://manto.9aia.com/schemas/role-permissions",
    $schema: "http://json-schema.org/draft-04/schema#",
    type: "array",
    description: "(Optional) A list of permissions for this role.",
    items: {
      type: "string",
      description: "A permission name (e.g., \"SendMessages\", \"ManageRoles\").",
      enum: Object.keys(PermissionFlagsBits),
    },
  }

  writeSchema(schema, "./src/schemas/manto-role-permissions.gen.jsonc")
}

function generateOverwritesPermissionsSchema() {
  const schema = {
    __comment__: true,
    id: "https://manto.9aia.com/schemas/overwrites-permissions",
    $schema: "http://json-schema.org/draft-04/schema#",
    type: "object",
    properties: Object.keys(PermissionFlagsBits).reduce((acc, key) => {
      acc[key] = {
        type: "string",
        enum: ["Allow", "Deny", "Default"],
      }
      return acc
    }, {} as Record<string, any>),
  }

  writeSchema(schema, "./src/schemas/manto-overwrites-permissions.gen.jsonc")
}

generateRolePermissionsSchema()
generateOverwritesPermissionsSchema()
